### ISSUE TITLE
VS 2022 support

### ISSUE THREAD

**Issue by Farb** [beatcracker/VSCELicense#14]
Visual Studio 2022 preview version has been released ,please support 2022.BTW ,2022 is a amazing 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by beatcracker** [comment]
Hi there! Usually I don't spend time on adding preview versions (https://github.com/beatcracker/VSCELicense/issues/1#issuecomment-462747072). But if it's really _amazing_ I might give it a try ;). No promises though.

**Comment by navrozashvili** [comment]
enterprise 2022 pre release registry key is Licenses\10D17DBA-761D-4CD8-A627-984E75A58700\09360 . It can be found using Sysinternals. Even tho adding days works even by just replacing 2019 key in https://github.com/l3afblow3r/VSEELicense it wont add more than 15 days. better than nothing.

https://github.com/navrozashvili/VSEELicense

**Comment by beatcracker** [comment]
I've pushed [vs2022](https://github.com/beatcracker/VSCELicense/tree/vs2022) branch which supports VS CE 2022 Preview. But as @navrozashvili mentioned, VS will only give you 15 days when you reset date in registry. I guess it's a preview limitation.

As soon as VS 2022 is finally released, I'll remove this branch and merge final 2022 support to the `master`.

**Comment by Farb** [comment]
> I've pushed [vs2022](https://github.com/beatcracker/VSCELicense/tree/vs2022) branch which supports VS CE 2022 Preview. But as @navrozashvili mentioned, VS will only give you 15 days when you reset date in registry. I guess it's a preview limitation.
> 
> As soon as VS 2022 is finally released, I'll remove this branch and merge final 2022 support to the `master`.

Does it work for you? Why doesn't it work for me😪

**Comment by navrozashvili** [comment]
> > I've pushed [vs2022](https://github.com/beatcracker/VSCELicense/tree/vs2022) branch which supports VS CE 2022 Preview. But as @navrozashvili mentioned, VS will only give you 15 days when you reset date in registry. I guess it's a preview limitation.
> > As soon as VS 2022 is finally released, I'll remove this branch and merge final 2022 support to the `master`.
> 
> Does it work for you? Why doesn't it work for me😪

New key:
Licenses\10D17DBA-761D-4CD8-A627-984E75A58700\09**4**60
but it wont add more than 7 days

**Comment by Farb** [comment]
@beatcracker Where is the new key?There's not the new key you gave in my registry .
![AE8494A3-8134-4C44-BFA8-3699604DBE03](https://user-images.githubusercontent.com/7587900/129570377-4a2ed523-df78-4c3e-9288-d636014c3fc8.jpeg)

**Comment by Farb** [comment]
@beatcracker @navrozashvili
I have upgraded the vs2022 to 17.0.0 Preview 3.1,and I found the new key is 09478,then I modified the .psm1 file for the new key.Finally ,I ran my AddDays.ps1 scripts and printed Success  string and vs2022 expire date is right .But it still shows "Your trial has expired " page .What reason?

![F79D6ED4-AF24-4B5A-87BE-30E937BCA7BC](https://user-images.githubusercontent.com/7587900/130022808-afa37eb9-7ebd-4aef-826b-ab50f5bbc4c6.png)
![9FE825E7-3EBF-43AC-93D0-589D469759DF](https://user-images.githubusercontent.com/7587900/130022817-4d99fcde-6bff-437a-98a6-7005faf2a11e.png)
![FA6201AA-793E-4C33-A605-9C4B0E4DFAAC](https://user-images.githubusercontent.com/7587900/130022861-bfc3b001-0109-4f7e-b348-2d2451af633a.png)

**Comment by navrozashvili** [comment]
> @beatcracker @navrozashvili
> I have upgraded the vs2022 to 17.0.0 Preview 3.1,and I found the new key is 09478,then I modified the .psm1 file for the new key.Finally ,I ran my AddDays.ps1 scripts and printed Success string and vs2022 expire date is right .But it still shows "Your trial has expired " page .What reason?
> 
> ![F79D6ED4-AF24-4B5A-87BE-30E937BCA7BC](https://user-images.githubusercontent.com/7587900/130022808-afa37eb9-7ebd-4aef-826b-ab50f5bbc4c6.png)
> ![9FE825E7-3EBF-43AC-93D0-589D469759DF](https://user-images.githubusercontent.com/7587900/130022817-4d99fcde-6bff-437a-98a6-7005faf2a11e.png)
> ![FA6201AA-793E-4C33-A605-9C4B0E4DFAAC](https://user-images.githubusercontent.com/7587900/130022861-bfc3b001-0109-4f7e-b348-2d2451af633a.png)

Once it expires I believe some registry key is set in a private hive and changing that license key has no effect.

**Comment by Farb** [comment]
@navrozashvili so,there's no way to solve it,right?😂

**Comment by navrozashvili** [comment]
> @navrozashvili so,there's no way to solve it,right?😂

1) reinstall vs 
2) mess with their hive(I really suggest against it, I ended up overwriting my HKCU and bricking my windows user last time I did it😂)

**Comment by Farb** [comment]
@navrozashvili Maybe I should give up .Because I have reinstalled it for several times .It didn't work. 😔

**Comment by Farb** [comment]
@navrozashvili 
Finally ,I solved the problem by offline registration 🤓The link is https://blog.csdn.net/songfuliang2011/article/details/102486451 .
![8D9A399A-A5C2-4C4F-A531-580A05CBD066](https://user-images.githubusercontent.com/7587900/130267808-9434aba5-52fb-4495-8132-988b55ba465f.png)

**Comment by undergroundwires** [comment]
The new registry key seems to be `B16F0CF0-8AD1-4A5B-87BC-CB0DBE9C48FC` and subkey is `09560`. I have preview 4.1. I could set the expiration date when I changed the keys but still get "Your trial has expired"

**Comment by undergroundwires** [comment]
The new registry key seems to be `B16F0CF0-8AD1-4A5B-87BC-CB0DBE9C48FC` and subkey is `09560`. I have preview 4.1. I could set the expiration date when I changed the keys but still get "Your trial has expired"

@Farb the link is dead, would you like to share how you solved it on your hand?

**Comment by Farb** [comment]
> The new registry key seems to be `B16F0CF0-8AD1-4A5B-87BC-CB0DBE9C48FC` and subkey is `09560`. I have preview 4.1. I could set the expiration date when I changed the keys but still get "Your trial has expired"
> 
> @Farb the link is dead, would you like to share how you solved it on your hand?

The link is available. But the article language is Chinese, maybe you should translate the page. The essential is copying license metadata from a computer that you can login to another computer that you cannot login.

**Comment by ednt** [comment]
I just installed the official VSCE 2022 and I found the key
`1299B4B9-DFCC-476D-98F0-F65A2B46C96D`
If I try `09678` I get 255,255,255,255,255 as date value, which is wrong.

**Comment by beatcracker** [comment]
Yep folks, gotta have a look at this as soon as I get a free minute.

**Comment by beatcracker** [comment]
Well, it looks like VS 2022 doesn't have any limits at all. I've installed it and moved clock to the year 2022 and back - no issues. And the license text says `Product key applied` instead of `30 days trial (evaluation period)` :partying_face:

![image](https://user-images.githubusercontent.com/7583050/141174317-11b8dcb2-5c71-4cbb-bd75-ee011f648763.png)

**Comment by lorisleitner** [comment]
The new key is `1299B4B9-DFCC-476D-98F0-F65A2B46C96D\09660`

Works for my VS22 Enterprise

**Comment by nasusonetrick** [comment]
is it possible to increase Expiration of years instead of just days ?

**Comment by beatcracker** [comment]
@nasusonetrick I don't thinks so: looks like the limit is built-in into the VS expiration date checking code. It ignores anything larger then 31 days.

**Comment by cirizo** [comment]
as with the current version it seems not to work anymore year comes back as 9680 month is 0 and day is 0

**Comment by LexaGV** [comment]
@beatcracker Unf. VS2022 **has** the limit! In my 17.12 Ent LTSC it says "you have 10 days" (of course I didn't sign in). So topic is actual and let's support 2022 too (esp. when it's the most actual version).

What is funny, for `Get-VSCELicenseExpirationDate` I have EMPTY reply. Should anything be written on a screen??
